version: "3.8"

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  testdb:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
      PGPORT: 5433
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    restart: always

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
    environment:
      - MODE=testing
      - SQLALCHEMY_DATABASE_URI=postgresql://testuser:testpassword@testdb:5433/testdb
      - JWT_SECRET_KEY=super-secret-key
    depends_on:
      - testdb
    volumes:
      - .:/app

volumes:
  postgres_data:
  test_postgres_data:
