# Use the official Python image
FROM python:3.12-slim

ENV MODE=testing

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install pytest pytest-flask pytest-mock

# Run pytest
CMD ["pytest"]